version: "3"
services:
  mongo:
    container_name: usr_mgt_db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=usermanagement
    networks:
      - usr-mgt-net
    volumes:
      - mongo-data:/data/db
  app:
    container_name: usr_mgt_api
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB: "usermanagement"
      MONGO_URI: mongodb://mongo:27017
      APP_ENV: "development"
      JWT_SECRET_KEY: "secret"
    networks:
      - usr-mgt-net
    volumes:
      - mongo-data:/data/db
    depends_on:
      - mongo
networks:
  usr-mgt-net:
    driver: bridge
volumes:
  mongo-data:
    driver: local